# Generated by Django 3.2.11 on 2022-05-24 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_files', models.ImageField(blank=True, null=True, upload_to='transpired_description/')),
                ('identity_verification', models.FileField(blank=True, null=True, upload_to='identity_verification/')),
                ('date_reported', models.DateTimeField(blank=True, null=True)),
                ('type_of_violation', models.CharField(blank=True, choices=[('Forced displacement', 'Forced displacement'), ('Exposure to pollutants', 'Exposure to pollutants'), ('Loss of land or economic assets', 'Loss of land or economic assets'), ('Desecration of cultural heritage including graves', 'Desecration of cultural heritage including graves'), ('Torture, intimidation and harassment', 'Torture, intimidation and harassment'), ('Curtailed freedom of movement', 'Curtailed freedom of movement'), ('Exposure to degraded environment', 'Exposure to degraded environment'), ('Limited access to water', 'Limited access to water'), ('Denied access to social services like Health facilities, School, Markets place', 'Denied access to social services like Health facilities, School, Markets place'), ('Forced and unpaid labour', 'Forced and unpaid labour'), ('Child labour', 'Child labour'), ('Murder or killings', 'Murder or killings')], max_length=250, null=True)),
                ('fd_how_many_removed', models.CharField(blank=True, max_length=250, null=True)),
                ('fd_alternative_place', models.CharField(blank=True, max_length=250, null=True)),
                ('fd_alternative_place_description', models.CharField(blank=True, max_length=250, null=True)),
                ('ep_what_kind', models.CharField(blank=True, max_length=250, null=True)),
                ('ep_source', models.CharField(blank=True, max_length=250, null=True)),
                ('ep_source_description', models.CharField(blank=True, max_length=250, null=True)),
                ('ep_num_people_exposed', models.CharField(blank=True, max_length=250, null=True)),
                ('ep_who_is_responsible', models.CharField(blank=True, max_length=250, null=True)),
                ('ll_assests_lost', models.CharField(blank=True, max_length=250, null=True)),
                ('ll_who_is_responsible', models.CharField(blank=True, max_length=250, null=True)),
                ('ll_families_affected', models.CharField(blank=True, max_length=250, null=True)),
                ('dc_how_many_graves', models.CharField(blank=True, max_length=250, null=True)),
                ('dc_who_desecrated_them', models.CharField(blank=True, max_length=250, null=True)),
                ('ti_type', models.CharField(blank=True, max_length=250, null=True)),
                ('ti_other', models.CharField(blank=True, max_length=250, null=True)),
                ('ti_groups_affected', models.CharField(blank=True, max_length=250, null=True)),
                ('ti_who_did_this', models.CharField(blank=True, max_length=250, null=True)),
                ('ti_company_involved', models.CharField(blank=True, max_length=250, null=True)),
                ('ti_the_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('rf_company_involved', models.CharField(blank=True, max_length=250, null=True)),
                ('la_company_involved', models.CharField(blank=True, max_length=250, null=True)),
                ('fu_company_involved', models.CharField(blank=True, max_length=250, null=True)),
                ('cl_company_involved', models.CharField(blank=True, max_length=250, null=True)),
                ('cl_number_of_children', models.CharField(blank=True, max_length=250, null=True)),
                ('es_which_resource', models.CharField(blank=True, max_length=250, null=True)),
                ('es_who_is_smuggling', models.CharField(blank=True, max_length=250, null=True)),
                ('es_company_involved', models.CharField(blank=True, max_length=250, null=True)),
                ('sv_affected_people', models.CharField(blank=True, max_length=250, null=True)),
                ('sv_type', models.CharField(blank=True, max_length=250, null=True)),
                ('sv_company_involved', models.CharField(blank=True, max_length=250, null=True)),
                ('sv_who_did_this', models.CharField(blank=True, max_length=250, null=True)),
                ('mk_groups_of_persons', models.CharField(blank=True, max_length=250, null=True)),
                ('mk_number_of_people', models.CharField(blank=True, max_length=250, null=True)),
                ('mk_how_they_died', models.CharField(blank=True, max_length=250, null=True)),
                ('mk_murder_other', models.CharField(blank=True, max_length=250, null=True)),
                ('mk_company_involved', models.CharField(blank=True, max_length=250, null=True)),
                ('what_happened', models.CharField(blank=True, max_length=250, null=True)),
                ('reporter_phone', models.CharField(blank=True, max_length=250, null=True)),
                ('reporter_address', models.CharField(blank=True, max_length=250, null=True)),
                ('reporter_email', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_area', models.CharField(blank=True, max_length=250, null=True)),
                ('village', models.CharField(blank=True, max_length=250, null=True)),
                ('chief', models.CharField(blank=True, max_length=250, null=True)),
                ('ward_name', models.CharField(blank=True, max_length=250, null=True)),
                ('district', models.CharField(blank=True, max_length=250, null=True)),
                ('province', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('collection_vp', models.JSONField(default=dict)),
                ('media_files', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners', models.CharField(max_length=250)),
                ('when_it_started_operating', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
