# Generated by Django 3.2.11 on 2022-06-06 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence_files/', verbose_name='The actual file')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='ReportedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateTimeField(blank=True, null=True, verbose_name='Date of incident')),
                ('type_of_violation', models.CharField(blank=True, choices=[('Forced displacement', 'Forced displacement'), ('Exposure to pollutants', 'Exposure to pollutants'), ('Loss of land or economic assets', 'Loss of land or economic assets'), ('Desecration of cultural heritage including graves', 'Desecration of cultural heritage including graves'), ('Torture, intimidation and harassment', 'Torture, intimidation and harassment'), ('Curtailed freedom of movement', 'Curtailed freedom of movement'), ('Exposure to degraded environment', 'Exposure to degraded environment'), ('Limited access to water', 'Limited access to water'), ('Denied access to social services like Health facilities, School, Markets place', 'Denied access to social services like Health facilities, School, Markets place'), ('Forced and unpaid labour', 'Forced and unpaid labour'), ('Child labour', 'Child labour'), ('Murder or killings', 'Murder or killings')], max_length=250, null=True, verbose_name='Type of violation')),
                ('fd_how_many_removed', models.CharField(blank=True, max_length=250, null=True, verbose_name='How many people have been forcibly displaced?')),
                ('fd_alternative_place', models.CharField(blank=True, max_length=250, null=True, verbose_name='Have they been offered alternative places to stay?')),
                ('fd_alternative_place_description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Have they been offered alternative places to stay (Optional description)')),
                ('ep_what_kind', models.CharField(blank=True, max_length=250, null=True, verbose_name='What kind of pollution have they been exposed to?')),
                ('ep_source', models.CharField(blank=True, max_length=250, null=True, verbose_name='What is the source of the pollution?')),
                ('ep_source_description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Optional description of source of pollution')),
                ('ep_num_people_exposed', models.CharField(blank=True, max_length=250, null=True, verbose_name='How many people have been exposed to this pollution?')),
                ('ep_who_is_responsible', models.CharField(blank=True, max_length=250, null=True, verbose_name='Who is responsible for the pollution (name of company)?')),
                ('ll_assests_lost', models.CharField(blank=True, max_length=250, null=True, verbose_name='What economic assets have you lost ? - livestock, agricultural land, other specify')),
                ('ll_who_is_responsible', models.CharField(blank=True, max_length=250, null=True, verbose_name='Who is responsible for the loss (company name)?')),
                ('ll_families_affected', models.CharField(blank=True, max_length=250, null=True, verbose_name='How many families were affected?')),
                ('dc_how_many_graves', models.CharField(blank=True, max_length=250, null=True, verbose_name='How many sites were desecrated?')),
                ('dc_who_desecrated_them', models.CharField(blank=True, max_length=250, null=True, verbose_name='Who desecrated them?')),
                ('ti_type', models.JSONField(blank=True, default=dict, null=True, verbose_name='Type of torture, intimidation, harassment')),
                ('ti_other', models.CharField(blank=True, max_length=250, null=True, verbose_name='Other type of harassment')),
                ('ti_groups_affected', models.CharField(blank=True, max_length=250, null=True, verbose_name='Which groups of people were affected ?')),
                ('ti_who_did_this', models.CharField(blank=True, max_length=250, null=True, verbose_name='Who did this ?')),
                ('ti_company_involved', models.CharField(blank=True, max_length=250, null=True, verbose_name='Which company was involved ?')),
                ('ti_the_reason', models.CharField(blank=True, max_length=250, null=True, verbose_name='What did they say was the reason for this ?')),
                ('rf_company_involved', models.CharField(blank=True, max_length=250, null=True, verbose_name='Restricted freedom of movement (Which company was involved?)')),
                ('la_company_involved', models.CharField(blank=True, max_length=250, null=True, verbose_name='Limited access to water (Which company was involved?)')),
                ('fu_company_involved', models.CharField(blank=True, max_length=250, null=True, verbose_name='Forced and unpaid labour (Which company was involved?)')),
                ('cl_company_involved', models.CharField(blank=True, max_length=250, null=True, verbose_name='Child labour (Which company was involved?)')),
                ('cl_number_of_children', models.CharField(blank=True, max_length=250, null=True, verbose_name='Child labour (Number of children involved)')),
                ('sv_affected_people', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sexual violence (Who is / are affected ?)')),
                ('sv_type', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sexual violence (Type of sexual violence)')),
                ('sv_company_involved', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sexual violence (Which company was involved ?)')),
                ('sv_who_did_this', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sexual violence (Who did this?)')),
                ('mk_groups_of_persons', models.CharField(blank=True, max_length=250, null=True, verbose_name='Murder or killings (Groups of persons murdered)')),
                ('mk_number_of_people', models.CharField(blank=True, max_length=250, null=True, verbose_name='Murder or killings (Number of people killed)')),
                ('mk_how_they_died', models.CharField(blank=True, max_length=250, null=True, verbose_name='Murder or killings (How the people were killed)')),
                ('mk_murder_other', models.CharField(blank=True, max_length=250, null=True, verbose_name='Murder or killings (Description for other weapons)')),
                ('mk_company_involved', models.CharField(blank=True, max_length=250, null=True, verbose_name='Murder or killings (Company involved)')),
                ('what_happened', models.CharField(blank=True, max_length=250, null=True, verbose_name='Full description of what happened')),
                ('reporter_phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Phone number of the reporter')),
                ('reporter_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address of the reporter')),
                ('reporter_email', models.CharField(blank=True, max_length=250, null=True, verbose_name='Email of the reporter')),
                ('name_of_area', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of the area')),
                ('village', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of the village')),
                ('chief', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of the chief')),
                ('ward_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of the ward')),
                ('district', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of the district')),
                ('province', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of the province')),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of the location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Latitude coordinates')),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Longitude coordinates')),
                ('collection_vp', models.JSONField(blank=True, default=dict, null=True, verbose_name='Collection of victims and perpetrators')),
                ('media_files', models.JSONField(blank=True, default=dict, null=True, verbose_name='Collection of the images, videos and audios')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners', models.CharField(max_length=250)),
                ('when_it_started_operating', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
