# Generated by Django 3.2.11 on 2022-05-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence_files/', verbose_name='The actual file')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='collection_vp',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='media_files',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='type_of_violation',
            field=models.CharField(blank=True, choices=[('Forced displacement', 'Forced displacement'), ('Exposure to pollutants', 'Exposure to pollutants'), ('Loss of land or economic assets', 'Loss of land or economic assets'), ('Desecration of cultural heritage including graves', 'Desecration of cultural heritage including graves'), ('Torture, intimidation and harassment', 'Torture, intimidation and harassment'), ('Curtailed freedom of movement', 'Curtailed freedom of movement'), ('Exposure to degraded environment', 'Exposure to degraded environment'), ('Limited access to water', 'Limited access to water'), ('Denied access to social services like Health facilities, School, Markets place', 'Denied access to social services like Health facilities, School, Markets place'), ('Forced and unpaid labour', 'Forced and unpaid labour'), ('Child labour', 'Child labour'), ('Murder or killings', 'Murder or killings')], max_length=250, null=True, verbose_name='Type of violation'),
        ),
    ]
