# Generated by Django 3.2.11 on 2022-05-21 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedcase',
            name='date_reported',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='description_of_perpetrator',
            field=models.CharField(blank=True, choices=[('Member of Parliament', 'Member of Parliament'), ('Mining company security guards', 'Mining company security guards'), ('Artisanal miners ', 'Artisanal miners '), ('Politician', 'Politician'), ('Government security agencies (police, army)', 'Government security agencies (police, army)'), ('Councilors', 'Councilors')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='description_of_victims',
            field=models.CharField(blank=True, choices=[('Community member (individual/group)', 'Community member (individual/group)'), ('Women', 'Women'), ('Girls', 'Girls'), ('Youth', 'Youth'), ('Household', 'Household'), ('Mining company', 'Mining company'), ('Traditional leader', 'Traditional leader'), ('Farmer', 'Farmer'), ('Community activist', 'Community activist'), ('School children', 'School children')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='evidence_files',
            field=models.ImageField(blank=True, null=True, upload_to='transpired_description/'),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='identity_verification',
            field=models.FileField(blank=True, null=True, upload_to='identity_verification/'),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='motivations_behind_incident',
            field=models.CharField(blank=True, choices=[('Political', 'Political'), ('To conceal illicit activities and corruption', 'To conceal illicit activities and corruption'), ('To exercise Power', 'To exercise Power'), ('To instill fear', 'To instill fear'), ('Economic interest', 'Economic interest')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='type_of_violation',
            field=models.CharField(blank=True, choices=[('Forced Displacement', 'Forced Displacement'), ('Exposure to pollutants', 'Exposure to pollutants'), ('Loss of land or economic assets', 'Loss of land or economic assets'), ('Desecration of cultural heritage including graves', 'Desecration of cultural heritage including graves'), ('Torture and intimidation / harrassment', 'Torture and intimidation / harrassment'), ('Curtailed freedom of movement', 'Curtailed freedom of movement'), ('Exposure to degraded environment', 'Exposure to degraded environment'), ('Limited access to water', 'Limited access to water'), ('Denied access to social services like Health facilities, School, Markets place', 'Denied access to social services like Health facilities, School, Markets place'), ('Forced and unpaid labour', 'Forced and unpaid labour'), ('Child labour', 'Child labour'), ('Murder / killings', 'Murder / killings')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
