# Generated by Django 3.2.11 on 2022-03-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220210_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business',
        ),
    ]
